/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as TimelineRouteImport } from './routes/timeline'
import { Route as TrendsRouteImport } from './routes/trends'
import { Route as AccountIndexRouteImport } from './routes/account/index'
import { Route as AccountDevicesRouteImport } from './routes/account/devices'
import { Route as AccountLanguageRouteImport } from './routes/account/language'
import { Route as AccountNotificationsRouteImport } from './routes/account/notifications'
import { Route as AccountPrivacyRouteImport } from './routes/account/privacy'
import { Route as AccountSecurityRouteImport } from './routes/account/security'
import { Route as AuthConsentRouteImport } from './routes/auth/consent'
import { Route as AuthForgotRouteImport } from './routes/auth/forgot'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthTwoFactorRouteImport } from './routes/auth/two-factor'
import { Route as RecordsIndexRouteImport } from './routes/records/index'
import { Route as RecordsRecordIdRouteImport } from './routes/records/$recordId'
import { Route as SessionIndexRouteImport } from './routes/session/index'
import { Route as SessionActiveRouteImport } from './routes/session/active'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const TimelineRoute = TimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const TrendsRoute = TrendsRouteImport.update({
  id: '/trends',
  path: '/trends',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AccountRoute,
} as any)
const AccountDevicesRoute = AccountDevicesRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => AccountRoute,
} as any)
const AccountLanguageRoute = AccountLanguageRouteImport.update({
  id: '/language',
  path: '/language',
  getParentRoute: () => AccountRoute,
} as any)
const AccountNotificationsRoute = AccountNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AccountRoute,
} as any)
const AccountPrivacyRoute = AccountPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => AccountRoute,
} as any)
const AccountSecurityRoute = AccountSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AccountRoute,
} as any)
const AuthConsentRoute = AuthConsentRouteImport.update({
  id: '/auth/consent',
  path: '/auth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotRoute = AuthForgotRouteImport.update({
  id: '/auth/forgot',
  path: '/auth/forgot',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthTwoFactorRoute = AuthTwoFactorRouteImport.update({
  id: '/auth/two-factor',
  path: '/auth/two-factor',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordsIndexRoute = RecordsIndexRouteImport.update({
  id: '/records/',
  path: '/records/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordsRecordIdRoute = RecordsRecordIdRouteImport.update({
  id: '/records/$recordId',
  path: '/records/$recordId',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionIndexRoute = SessionIndexRouteImport.update({
  id: '/session/',
  path: '/session/',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionActiveRoute = SessionActiveRouteImport.update({
  id: '/session/active',
  path: '/session/active',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/onboarding': typeof OnboardingRoute
  '/timeline': typeof TimelineRoute
  '/trends': typeof TrendsRoute
  '/account/devices': typeof AccountDevicesRoute
  '/account/language': typeof AccountLanguageRoute
  '/account/notifications': typeof AccountNotificationsRoute
  '/account/privacy': typeof AccountPrivacyRoute
  '/account/security': typeof AccountSecurityRoute
  '/auth/consent': typeof AuthConsentRoute
  '/auth/forgot': typeof AuthForgotRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/two-factor': typeof AuthTwoFactorRoute
  '/records/$recordId': typeof RecordsRecordIdRoute
  '/session/active': typeof SessionActiveRoute
  '/account/': typeof AccountIndexRoute
  '/records/': typeof RecordsIndexRoute
  '/session/': typeof SessionIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/onboarding': typeof OnboardingRoute
  '/timeline': typeof TimelineRoute
  '/trends': typeof TrendsRoute
  '/account/devices': typeof AccountDevicesRoute
  '/account/language': typeof AccountLanguageRoute
  '/account/notifications': typeof AccountNotificationsRoute
  '/account/privacy': typeof AccountPrivacyRoute
  '/account/security': typeof AccountSecurityRoute
  '/auth/consent': typeof AuthConsentRoute
  '/auth/forgot': typeof AuthForgotRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/two-factor': typeof AuthTwoFactorRoute
  '/records/$recordId': typeof RecordsRecordIdRoute
  '/session/active': typeof SessionActiveRoute
  '/account': typeof AccountIndexRoute
  '/records': typeof RecordsIndexRoute
  '/session': typeof SessionIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/onboarding': typeof OnboardingRoute
  '/timeline': typeof TimelineRoute
  '/trends': typeof TrendsRoute
  '/account/devices': typeof AccountDevicesRoute
  '/account/language': typeof AccountLanguageRoute
  '/account/notifications': typeof AccountNotificationsRoute
  '/account/privacy': typeof AccountPrivacyRoute
  '/account/security': typeof AccountSecurityRoute
  '/auth/consent': typeof AuthConsentRoute
  '/auth/forgot': typeof AuthForgotRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/two-factor': typeof AuthTwoFactorRoute
  '/records/$recordId': typeof RecordsRecordIdRoute
  '/session/active': typeof SessionActiveRoute
  '/account/': typeof AccountIndexRoute
  '/records/': typeof RecordsIndexRoute
  '/session/': typeof SessionIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/dashboard'
    | '/onboarding'
    | '/timeline'
    | '/trends'
    | '/account/devices'
    | '/account/language'
    | '/account/notifications'
    | '/account/privacy'
    | '/account/security'
    | '/auth/consent'
    | '/auth/forgot'
    | '/auth/login'
    | '/auth/register'
    | '/auth/two-factor'
    | '/records/$recordId'
    | '/session/active'
    | '/account/'
    | '/records/'
    | '/session/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/onboarding'
    | '/timeline'
    | '/trends'
    | '/account/devices'
    | '/account/language'
    | '/account/notifications'
    | '/account/privacy'
    | '/account/security'
    | '/auth/consent'
    | '/auth/forgot'
    | '/auth/login'
    | '/auth/register'
    | '/auth/two-factor'
    | '/records/$recordId'
    | '/session/active'
    | '/account'
    | '/records'
    | '/session'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/dashboard'
    | '/onboarding'
    | '/timeline'
    | '/trends'
    | '/account/devices'
    | '/account/language'
    | '/account/notifications'
    | '/account/privacy'
    | '/account/security'
    | '/auth/consent'
    | '/auth/forgot'
    | '/auth/login'
    | '/auth/register'
    | '/auth/two-factor'
    | '/records/$recordId'
    | '/session/active'
    | '/account/'
    | '/records/'
    | '/session/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  OnboardingRoute: typeof OnboardingRoute
  TimelineRoute: typeof TimelineRoute
  TrendsRoute: typeof TrendsRoute
  AuthConsentRoute: typeof AuthConsentRoute
  AuthForgotRoute: typeof AuthForgotRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthTwoFactorRoute: typeof AuthTwoFactorRoute
  RecordsRecordIdRoute: typeof RecordsRecordIdRoute
  SessionActiveRoute: typeof SessionActiveRoute
  RecordsIndexRoute: typeof RecordsIndexRoute
  SessionIndexRoute: typeof SessionIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timeline': {
      id: '/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof TimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trends': {
      id: '/trends'
      path: '/trends'
      fullPath: '/trends'
      preLoaderRoute: typeof TrendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/': {
      id: '/account/'
      path: '/'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/devices': {
      id: '/account/devices'
      path: '/devices'
      fullPath: '/account/devices'
      preLoaderRoute: typeof AccountDevicesRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/language': {
      id: '/account/language'
      path: '/language'
      fullPath: '/account/language'
      preLoaderRoute: typeof AccountLanguageRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/notifications': {
      id: '/account/notifications'
      path: '/notifications'
      fullPath: '/account/notifications'
      preLoaderRoute: typeof AccountNotificationsRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/privacy': {
      id: '/account/privacy'
      path: '/privacy'
      fullPath: '/account/privacy'
      preLoaderRoute: typeof AccountPrivacyRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/security': {
      id: '/account/security'
      path: '/security'
      fullPath: '/account/security'
      preLoaderRoute: typeof AccountSecurityRouteImport
      parentRoute: typeof AccountRoute
    }
    '/auth/consent': {
      id: '/auth/consent'
      path: '/auth/consent'
      fullPath: '/auth/consent'
      preLoaderRoute: typeof AuthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot': {
      id: '/auth/forgot'
      path: '/auth/forgot'
      fullPath: '/auth/forgot'
      preLoaderRoute: typeof AuthForgotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/two-factor': {
      id: '/auth/two-factor'
      path: '/auth/two-factor'
      fullPath: '/auth/two-factor'
      preLoaderRoute: typeof AuthTwoFactorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/records/': {
      id: '/records/'
      path: '/records'
      fullPath: '/records/'
      preLoaderRoute: typeof RecordsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/records/$recordId': {
      id: '/records/$recordId'
      path: '/records/$recordId'
      fullPath: '/records/$recordId'
      preLoaderRoute: typeof RecordsRecordIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session/': {
      id: '/session/'
      path: '/session'
      fullPath: '/session/'
      preLoaderRoute: typeof SessionIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session/active': {
      id: '/session/active'
      path: '/session/active'
      fullPath: '/session/active'
      preLoaderRoute: typeof SessionActiveRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AccountRouteChildren {
  AccountDevicesRoute: typeof AccountDevicesRoute
  AccountLanguageRoute: typeof AccountLanguageRoute
  AccountNotificationsRoute: typeof AccountNotificationsRoute
  AccountPrivacyRoute: typeof AccountPrivacyRoute
  AccountSecurityRoute: typeof AccountSecurityRoute
  AccountIndexRoute: typeof AccountIndexRoute
}

const AccountRouteChildren: AccountRouteChildren = {
  AccountDevicesRoute: AccountDevicesRoute,
  AccountLanguageRoute: AccountLanguageRoute,
  AccountNotificationsRoute: AccountNotificationsRoute,
  AccountPrivacyRoute: AccountPrivacyRoute,
  AccountSecurityRoute: AccountSecurityRoute,
  AccountIndexRoute: AccountIndexRoute,
}

const AccountRouteWithChildren =
  AccountRoute._addFileChildren(AccountRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRouteWithChildren,
  DashboardRoute: DashboardRoute,
  OnboardingRoute: OnboardingRoute,
  TimelineRoute: TimelineRoute,
  TrendsRoute: TrendsRoute,
  AuthConsentRoute: AuthConsentRoute,
  AuthForgotRoute: AuthForgotRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthTwoFactorRoute: AuthTwoFactorRoute,
  RecordsRecordIdRoute: RecordsRecordIdRoute,
  SessionActiveRoute: SessionActiveRoute,
  RecordsIndexRoute: RecordsIndexRoute,
  SessionIndexRoute: SessionIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
